version: "3.9"
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        ports:
            - 5000:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: Todo
        volumes:
            - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
volumes:
    postgres-data:
